"""
Module for the configuration
of the Bag application.
"""
from django.apps import AppConfig


class BagConfig(AppConfig):
    """
    Configuration class for the 'bag' app.

    This class is auto-generated by Django and sets default configurations
    for the application, such as the default primary key field type.
    """
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'bag'
