from django.apps import AppConfig


class ProfilesConfig(AppConfig):
    """
    Configuration class for the 'home' app.

    This class is auto-generated by Django and sets default configurations 
    for the application, such as the default primary key field type.
    """
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'profiles'
